export const ROUTES = {
  home: "/",
  login: "/dang-nhap",
  register: "/dang-ky",
  forgotPassword: "/quen-mat-khau",
  resetPassword: "/dat-lai-mat-khau",
  verifyEmail: "/xac-thuc-email",
  unauthorized: "/khong-co-quyen",
  dashboard: "/tong-quan",
  library: "/thu-vien",
  upload: "/tai-len",
  community: "/cong-dong",
  saved: "/da-luu",
  askDocument: "/hoi-tai-lieu",
  askLibrary: "/hoi-thu-vien",
  subscription: "/goi-dich-vu",
  profile: "/ho-so",
  adminUsers: "/quan-tri/nguoi-dung",
  terms: "/dieu-khoan-dich-vu",
  privacy: "/chinh-sach-bao-mat",
} as const;
